name: 15-minute-cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: self-hosted
    steps:
      - name: Call our API route
        run: |
          curl --request POST -d "data=true" --url 'https://smee.io/VquzZJyUGYiCrEDD'
