name: 15-minute-cron
on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: self-hosted
    steps:
      - name: Call our API route
        run: |
          curl --request GET --url 'https://ifconfig.me'
