name: 15-minute-cron
on:
  workflow_dispatch:
  deployment:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: self-hosted
    steps:
      - name: Call our API route
        run: |
          curl --request POST -d "tt=tt" --url 'https://hooks.reisenbauer.at/events/pottenstein?token=rest1337'
