name: 15-minute-cron
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: self-hosted
    steps:
      - name: Call our API route
        run: |
          curl --request GET --url 'https://ifconfig.me'
