name: Docker Images

on:
  push:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build docker image 
      uses: docker/build-push-action@v2.9.0
      with:
        push: true
        tags: latest
