name: Docker Images

on:
  push:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ret1337/zte-mc801a-mqtt-bridge
        add_git_labels: true
        tags: latest
        tag_with_ref: true
        tag_with_sha: true